### PR TITLE
Fix error when quitting a scene

### PR DESCRIPTION
**Pull request by 4kxz**
After updating, I'm getting an error every time I debug a scene, when I quit() it complains that the tree is null.

This is the modified code I'm using to avoid the issue.

### CODE REVIEW

**Comment by 4kxz** [comment]
@ramokz It took some fiddling, turns out it only happens when nodes are in certain order. I was able to reproduce it here: [error-reproduction.zip](https://github.com/user-attachments/files/18219155/error-reproduction.zip)

**Comment by ramokz** [comment]
Thanks for sharing the reproducible project, can replicate and see the issue now.

Think there's a more elegant solution where it checks whether if the scene tree still exists further down the stack, so it doesn't do a series of needless checks. More so if other things were to rely on the scene tree at some point between then and where the issue occurs.

Reckon a more ideal solution would be to just do a simple check and then return the function before it kicks off any more of the logic:

(Line 569 in `phantom_camera_host.gd`)
```gdscript
func _find_pcam_with_highest_priority() -> void:

  if not get_tree(): return

  # Rest of the function
  for pcam in _pcam_list:
    if not pcam.visible: continue # Prevents hidden PCams from becoming active
    if pcam.get_priority() > _active_pcam_priority:
      _assign_new_active_pcam(pcam)
      pcam.set_tween_skip(self, false)
      _active_pcam_missing = false
```

**Comment by lord-muad-dib** [comment]
yeah, blocking it earlier is a better idea, since the scene is despawning anyways, no need to execute all the logic.
one thing though, using `if not inside_tree():` (on self, so no arguments) seems to be slightly faster.

sorry for not being around earlier! thankfully i wasn't the only one with this issue.

thanks

note: switching the scene from a singleton seems  to workaround the issue altogether. but it's better to have the plugin fixed and have it work on every situation rather than hack a way through!

**Comment by 4kxz** [comment]
Yes, is_inside_tree works nicely and it's just one line, I've updated the branch.

**Review by ramokz — APPROVED** [review]

**Comment by ramokz** [comment]
Looks good, thanks all!

**Pull request merged**
