### PR TITLE
Set Framed data on ready

### PR DESCRIPTION
**Pull request by warent**
Plus some minor cleanup

### CODE REVIEW

**Comment by ramokz** [comment]
Think this is looking fine!
However, I'm curious about the use cases where this is needed. Are you applying a `Follow Target` at runtime, via a setter method, as opposed to from the editor in your example? Mainly wondering if the fix might be a symptom of a bigger issue, which might require some more systemic changes.

**Comment by warent** [comment]
> Think this is looking fine! However, I'm curious about the use cases where this is needed. Are you applying a `Follow Target` at runtime, via a setter method, as opposed to from the editor in your example? Mainly wondering if the fix might be a symptom of a bigger issue, which might require some more systemic changes.

I'm not applying any settings at runtime afaik, actually not entirely sure why this happens. May have something to do with node initialization order? Didn't really dig in that deep to check, sorry

**Comment by ramokz** [comment]
Am hesitant to merge a fix to a bug that cannot be easily be reproduced.
I'll try and do some additional tests to figure out what might be causing the issue.

**Comment by ramokz** [comment]
Haven't been able to replicate the issue, as I'm still not entirely sure how to trigger it.

Would it be possible to share a simple scene, with as little or as many nodes/assets as you want, that reproduces the issue?

**Review by ramokz — APPROVED** [review]
Scratch my last comment, managed to replicate the issue somehow today in the existing `3DFollowFramedExampleScene.tscn` scene.

Still unsure what triggers it, which is a bit concerning, but your changes does solve the strange behaviour, so happy to merge this.

**Comment by ramokz** [comment]
Thanks for investigating the issue and submitting the fix! ✨

**Pull request merged**
