### PR TITLE
Changed PCam2D/3D from _process to _physics_process

### LINKED ISSUE #173: Jittery camera movement
### Issue description

I have a 144hz monitor and camera movement is very jittery in 3D and 2D when I have VSync on or framerate cap at an odd number.  From my limited testing it seems to be an issue when the physics process happens at a different framerate compare to the monitors refresh rate. One way I found to solve the issue is to change `_process` inside phantom camera code to `_physics_process` but I'm not sure if there are any side effects to doing that. I know that physics jitter is a known issue with Godot itself but I wonder if there is specific ways to properly avoid it with phantom camera since its going to be a problem if players will have inconsistent framerate too.

### Steps to reproduce

* Have VSync or framerate cap turned on 
* Make sure that physics ticks per second is a different number that is not divisible by by your monitor refresh rate (for example if you have a 60hz monitor change the physics ticks per second to different number that is not divisible by 60) 
* Check one of the example scenes like `2DExampleScene.tscn` or `3DFollowSimpleExampleScene.tscn` for jitter when the character moves around

### (Optional) Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ramokz**
Resolves #173

### CODE REVIEW

**Comment by P5ina** [comment]
I don't think this is good idea. If you need to remove jitter on physics objects you need to tween their visuals on your own. Camera is not a physics object, in most animations you use process to update positions

**Comment by P5ina** [comment]
I made my own PR, so this is correct fix of problem, so maybe you want to check it #179

**Comment by P5ina** [comment]
> I don't think this is good idea. If you need to remove jitter on physics objects you need to tween their visuals on your own. Camera is not a physics object, in most animations you use process to update positions

I made an explanation how to do it in #173

**Comment by ramokz** [comment]
Closing in favour of #179

**Pull request closed without merging**
